import type { Span } from "../../diagnostics.js";
import { cssVarName, type FileIR } from "../../ir/ir.js";

const HEADER = "// Generated by @arviahq/compiler - do not edit.";

const TS_IDENT_RE = /^[A-Za-z_$][A-Za-z0-9_$]*$/;

const key = (name: string) => (TS_IDENT_RE.test(name) ? name : JSON.stringify(name));

const FN_PREFIX = "export declare function ";

export interface DtsAnchor {
  name: string;
  sourceStart: number;
  sourceLength: number;
  generatedStart: number;
  generatedLength: number;
}

export function emitDts(ir: FileIR): string {
  return emitDtsWithAnchors(ir).code;
}

const CONST_PREFIX = "export declare const ";

/** `theme { color { ... } }` → `Color`; non-identifier results are skipped. */
function tokenAliasName(group: string): string | null {
  const pascal = group
    .split(/[-_]+/)
    .filter(Boolean)
    .map((part) => part[0]!.toUpperCase() + part.slice(1))
    .join("");
  const alias = `${pascal}Token`;
  return TS_IDENT_RE.test(alias) ? alias : null;
}

function emitTokensDts(ir: FileIR, takenNames: Set<string>): string[] {
  const groups = new Map<string, { name: string; doc: string | null; type: string }[]>();
  for (const v of ir.themeVars) {
    const entries = groups.get(v.group) ?? [];
    // Moded themes resolve through CSS custom properties, so the var() ref is
    // stable and can be a literal type; single-mode values are inlined
    // literals that may diverge on broken sources — type those as string.
    const type = ir.themeModes ? JSON.stringify(`var(${cssVarName(v.group, v.name)})`) : "string";
    entries.push({ name: v.name, doc: v.doc, type });
    groups.set(v.group, entries);
  }

  const groupParts: string[] = [];
  for (const [group, entries] of groups) {
    const lines = entries.map((e) => {
      const doc = e.doc ? `    /** ${e.doc.replaceAll("*/", "*\\/")} */\n` : "";
      return `${doc}    readonly ${key(e.name)}: ${e.type};`;
    });
    groupParts.push(`  readonly ${key(group)}: {\n${lines.join("\n")}\n  };`);
  }

  const parts = [`export declare const tokens: {\n${groupParts.join("\n")}\n};`];
  for (const group of groups.keys()) {
    const alias = tokenAliasName(group);
    if (!alias || takenNames.has(alias)) continue;
    takenNames.add(alias);
    parts.push(`export type ${alias} = keyof (typeof tokens)[${JSON.stringify(group)}];`);
  }
  return parts;
}

export function emitDtsWithAnchors(ir: FileIR): { code: string; anchors: DtsAnchor[] } {
  if (ir.components.length === 0 && ir.styles.length === 0 && ir.themeVars.length === 0) {
    return { code: `${HEADER}\nexport {};\n`, anchors: [] };
  }

  const parts: string[] = [HEADER];
  const fnDecls: { partIndex: number; name: string; nameSpan: Span; prefixLength: number }[] = [];
  for (const c of ir.components) {
    const slotsType = `export type ${c.name}Slots = {\n${c.slotNames
      .map((slot) => `  ${key(slot)}: string;`)
      .join("\n")}\n};`;

    if (c.variants.length > 0) {
      // A variant with no `defaults` entry has no fallback value, so omitting
      // it would silently render unstyled — surface that as a required prop.
      const props = c.variants
        .map((variant) => {
          const union =
            variant.values.length > 0
              ? variant.values.map((value) => JSON.stringify(value.name)).join(" | ")
              : "never";
          const required = !(variant.name in c.defaults);
          return `  ${key(variant.name)}${required ? "" : "?"}: ${union};`;
        })
        .join("\n");
      const anyRequired = c.variants.some((variant) => !(variant.name in c.defaults));
      parts.push(
        `export type ${c.name}Props = {\n${props}\n};`,
        slotsType,
        `${FN_PREFIX}${c.name}(props${anyRequired ? "" : "?"}: ${c.name}Props): ${c.name}Slots;`,
      );
    } else {
      parts.push(slotsType, `${FN_PREFIX}${c.name}(): ${c.name}Slots;`);
    }
    fnDecls.push({
      partIndex: parts.length - 1,
      name: c.name,
      nameSpan: c.nameSpan,
      prefixLength: FN_PREFIX.length,
    });
  }

  for (const s of ir.styles) {
    parts.push(`${CONST_PREFIX}${s.name}: string;`);
    fnDecls.push({
      partIndex: parts.length - 1,
      name: s.name,
      nameSpan: s.nameSpan,
      prefixLength: CONST_PREFIX.length,
    });
  }

  if (ir.themeVars.length > 0) {
    const takenNames = new Set<string>(["tokens"]);
    for (const c of ir.components) {
      takenNames.add(c.name).add(`${c.name}Props`).add(`${c.name}Slots`);
    }
    for (const s of ir.styles) takenNames.add(s.name);
    parts.push(...emitTokensDts(ir, takenNames));
  }

  const code = parts.join("\n\n") + "\n";

  const partOffsets: number[] = [];
  let offset = 0;
  for (let i = 0; i < parts.length; i++) {
    partOffsets[i] = offset;
    offset += parts[i]!.length + "\n\n".length;
  }

  const anchors = fnDecls.map((f) => ({
    name: f.name,
    sourceStart: f.nameSpan.start,
    sourceLength: f.nameSpan.end - f.nameSpan.start,
    generatedStart: partOffsets[f.partIndex]! + f.prefixLength,
    generatedLength: f.name.length,
  }));

  return { code, anchors };
}
